# Yleiset asetukset
sport: "NHL"
threshold_percent: 5.0

# Sivustojen URL-osoitteet ja valitsimet
sites:
  veikkaus:
    url: "https://www.veikkaus.fi/fi/vedonlyonti/urheilulajit/jaakiekko/nhl"
    event_selector: "div.ottelu"  # TODO: korvaa todellisella CSS-valitsimella
    team_selector: "span.joukkue"
    odds_selector: "span.kerroin"

  pinnacle:
    url: "https://www.pinnacle.com/en/hockey/nhl/matchups"
    event_selector: "div.event"
    team_selector: "span.team"
    odds_selector: "span.odds"

# Telegram-asetukset
telegram:
  token: "8193881799:AAFtA0WgTqnftePxmHH_XhtVSCXiQmhekgg"
  chat_id: "-1003125625250"
