sport: "NHL"
threshold_percent: 5.0
debug: true

sites:
  pinnacle:
    url: "https://www.pinnacle.com/en/hockey/nhl/matchups"
    event_selector: 'div[data-test-id^="row-"]'
    team_selector: 'span.ellipsis[class^="gameInfoLabel"]'
    money_container_selector: 'div[data-test-id="moneyline"]'
    price_selector: 'span[class^="price"]'

  veikkaus:
    list_url: "https://www.veikkaus.fi/fi/pitkaveto/fi/sports/competition/944/jaakiekko/usa/nhl/matches"

discord:
  webhook_url: ${DISCORD_WEBHOOK_URL}
